import './globals.css'; // 여기에 globals.css 파일을 임포트합니다.

export const metadata = {
  title: 'Next.js Bet App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}